export { default as Game } from './Game'
export { default as Menu } from './Menu'
export { default as Login } from './Login'
export { default as Registration } from './Registration'
export { default as PostGame } from './PostGame'
